import Head from "next/head";
import {
  AiFillLinkedin, AiFillGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import mern from "../public/mern.png";
import design from "../public/design.png";
import landing from "../public/landingg.png";
import Image from "next/image";
import ecommerce from "../public/screen.png"
import deporte360 from "../public/screen2.png"
import ParticlesBackground from "../components/ParticlesBackground";
import ParticlesConfig from "../components/ParticlesConfig";
const repositorio1 = "https://nicosici1.github.io/Ecommerce-vanilla-js/";
<<<<<<< HEAD
const repositorio2 = "https://github.com/nicosici1/Deporte-360-Noticias";
=======
const repositorio2 = "https://github.com/nicosici1/Deporte-360-Noticias.git";
>>>>>>> fd17488181cdb7d9ba6ce209555b104f59540a45




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (

    <>

      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40"> */}

        <main className=" bg-white px-10 dark:bg-neutral-900 md:px-20 lg:px-40">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between dark:text-white">
              <p className="font-fira text-xl">ns</p>
              {/* <Image src="./public/LogoSVG.svg" alt="Logo" width={32} height={32} className="w-8 h-8" /> */}
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                </li>
                <li>
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                    href="/CV-NicolasSiciliano.pdf"
                    target="_blank"
               
                  >
                    Resume
                  </a>
                </li>

              </ul>
            </nav>

            <div className="text-center p-10 py-10">
              <div className="m-5">
                <ParticlesBackground config={ParticlesConfig} className="h-[100vh] w-[100vw]" />
              </div>
              <div>
                <h1 className="text-5xl py-2 text-teal-600 font-bold dark:text-teal-400 md:text-6xl">
                  Nicolás Siciliano
                </h1>
                <h2 className="text-2xl py-2 font-medium dark:text-white md:text-3xl">
                  Software Developer.
                </h2>
                <p className="text-md py-5 font-regular leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                  {`Hi there! i'm always ready for new challenges in software development.
                  Lets create something amazing together!`}
                </p>
                <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                  <a href="https://www.linkedin.com/in/nicosici/" target="_blank" rel="noopener noreferrer">
                    <AiFillLinkedin />
                  </a>
                  <a href="https://github.com/nicosici1" target="_blank" rel="noopener noreferrer">
                    <AiFillGithub />
                  </a>
                </div>
                {/* <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 relative overflow-hidden mt-20 md:h-96 md:w-96">
                  <Image src={deved} layout="fill" objectFit="cover" alt="alt" />
                </div> */}
              </div>
            </div>
          </section>

      

          <section>
            <div>
              <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Below are the <span className="text-teal-500"> services </span> I offer as a software developer:
              </p>
            </div>
            <div className="lg:flex gap-10 ">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-neutral-800 text-black dark:text-white flex-1">{/* dark:bg-white */}
                <Image src={landing} width={100} height={100} alt="Landing" />
                <h3 className="text-lg font-medium pt-8 pb-2 ">Landing Pages</h3>
                <p className="py-2">
                  Create stunning and engaging landing pages using HTML, CSS, Bootstrap, Tailwind CSS, and JavaScript.
                  With a focus on aesthetics and user experience, deliver responsive and captivating landing pages that drive conversions.
                </p>
                <h4 className="py-4 text-teal-500">What I offer:</h4>
                <p className="text-teal-600 py-1">- Performance optimization for fast loading and smooth user experience</p>
                <p className="text-teal-600 py-1">- Responsive layouts optimized for various devices and screen sizes</p>
                <p className="text-teal-600 py-1">- Integration of interactive elements and animations</p>
                <p className="text-teal-600 py-1">- Custom landing page design and development</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10  bg-white dark:bg-neutral-800 text-black dark:text-white flex-1">
                <Image src={design} width={100} height={100} alt="Photoshop" />
                <h3 className="text-lg font-medium pt-8 pb-2  ">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  {`Create elegant and visually stunning designs tailored to your specific needs, while adhering to core design theory principles.
                  Whether it's a website, logo, or marketing material, I believe in the power of design to make a lasting impression and effectively communicate your message.`}
                </p>
                <h4 className="py-4 text-teal-500">Design Tools I Use</h4>
                <p className="text-teal-600 py-1">Photoshop</p>
                <p className="text-teal-600 py-1">Illustrator</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-white dark:bg-neutral-800 text-black dark:text-white flex-1">
                <Image src={mern} width={100} height={100} alt="Mern" />
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  MERN Stack
                </h3>
                <p className="py-2">
                  I excel in developing web applications, leveraging the power of the MERN stack (MongoDB, Express, React, Node.js).
                   My expertise lies in crafting scalable, robust, and high-performance applications that precisely align with your unique requirements. 
                   In addition to my proficiency in the MERN stack, I possess extensive knowledge of various other technologies and frameworks, which enables me to offer versatile and efficient solutions tailored to your needs.
                </p>
                <h4 className="py-4 text-teal-500">What I offer:</h4>
                <p className="text-teal-600 py-1">Integration of various libraries and development tools</p>
                <p className="text-teal-600 py-1">Building RESTful APIs with Node.js and Express.js</p>
                <p className="text-teal-600 py-1">Frontend development using React.js</p>
                <p className="text-teal-600 py-1">Database management with MongoDB</p>
              </div>
            </div>
          </section>


          <section className="py-10">
            <div>
              <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                {`Welcome to my portfolio! Here, you can explore some of the projects I've developed during my time
                in university. These projects were completed as part of my coursework and demonstrate my skills
                and proficiency in software development.`}
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Although these projects were not commissioned by agencies or startups, they showcase my ability to tackle various programming challenges and apply theoretical knowledge to real-world scenarios.
                Feel free to browse through and get a glimpse of my capabilities as a software developer.
              </p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1 ">
                <a href={repositorio1} target="_blank" rel="noopener noreferrer">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={ecommerce}
                    alt="alt"
                  />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href={repositorio2} target="_blank" rel="noopener noreferrer">
                  <Image
                    className="rounded-lg object-cover"
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    src={deporte360}
                    alt="alt"
                  />
                </a>
              </div>
            </div>
          </section>

        </main>

        <footer
          className={`text-center py-5 text-gray-600 dark:text-gray-400 ${darkMode ? "bg-neutral-800" : "bg-white"
            }`}
        >
          <p>Nicolas Siciliano © 2023</p>
          <div className="flex justify-center gap-4 mt-4">
            <div className="w-8 h-8 bg-teal-500"></div>
            <div className="w-8 h-8 bg-cyan-500"></div>
            <div className={darkMode ? "w-8 h-8 bg-white" : "w-8 h-8 bg-neutral-800"}></div>
          </div>
        </footer>



      </div >



    </>



  );
}

